workflows:
  upahar-customer:
    name: Upahar Customer App
    environment:
      groups:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.upahar.customer"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com