dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.5
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.1
  url_launcher: ^6.1.10  # ADD THIS LINE
  
  # Firebase Dependencies
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.17.1
  firebase_storage: ^11.5.4
  firebase_analytics: ^10.7.4
  
  # Additional Helpers
  image_picker: ^1.0.4
  shared_models:
    path: ../shared_models
